name: SkyBlockInVanilla
version: 1.2.0
main: misc.Plugin
api-version: '1.21.4'

commands:
  getopitems:
    description: Get insanely overpowered SkyBlock items!  Valid itemSets - combat, ingredient, summon
    usage: /getopitems [itemSet] <player>
  w:
    description: Whisper messages to another player!
    usage: /w [player] [message]
  locateplayer:
    description: Locate a player on the server!
    usage: /locateplayer [player]
  resetwitherfight:
    description: Resets the status of the Wither Lords boss fight.  Useful if the boss was /kill'ed or otherwise dead in an unintended way.
    usage: /resetwitherfight

depend:
  - UltimateAdvancementAPI